"""Built-in test definitions (the seed catalog).

Each maps to a failure mode in the mock (X-Failure-Mode header). The evaluation
suite (app.eval.run) iterates these to measure diagnosis accuracy.
"""

BUILTIN_TESTS = [
    # --- auth / catalog ---
    {"name": "Fetch catalog with valid token", "category": "catalog",
     "method": "GET", "path": "/mock/catalog", "expected_status": 200,
     "headers": {"Authorization": "Bearer valid_token_abc"}, "body": None, "failure_mode": None},
    {"name": "Fetch catalog with missing token", "category": "catalog",
     "method": "GET", "path": "/mock/catalog", "expected_status": 401,
     "headers": {}, "body": None, "failure_mode": None},
    {"name": "Fetch catalog with invalid token", "category": "catalog",
     "method": "GET", "path": "/mock/catalog", "expected_status": 401,
     "headers": {"Authorization": "Bearer valid_token_abc"}, "body": None, "failure_mode": "invalid-token"},
    {"name": "Fetch catalog with expired token", "category": "catalog",
     "method": "GET", "path": "/mock/catalog", "expected_status": 401,
     "headers": {"Authorization": "Bearer expired_token_123"}, "body": None, "failure_mode": None},
    {"name": "Fetch catalog with wrong api version", "category": "catalog",
     "method": "GET", "path": "/mock/catalog", "expected_status": 400,
     "headers": {"Authorization": "Bearer valid_token_abc", "x-api-version": "9"}, "body": None, "failure_mode": None},
    {"name": "Fetch catalog rate limited", "category": "catalog",
     "method": "GET", "path": "/mock/catalog", "expected_status": 429,
     "headers": {"Authorization": "Bearer valid_token_abc"}, "body": None, "failure_mode": "rate-limited"},
    {"name": "Fetch catalog returns malformed response", "category": "catalog",
     "method": "GET", "path": "/mock/catalog", "expected_status": 200,
     "headers": {"Authorization": "Bearer valid_token_abc"}, "body": None, "failure_mode": "malformed-response"},
    {"name": "Fetch catalog server error", "category": "catalog",
     "method": "GET", "path": "/mock/catalog", "expected_status": 500,
     "headers": {"Authorization": "Bearer valid_token_abc"}, "body": None, "failure_mode": "server-error"},
    # --- orders ---
    {"name": "Create order with valid token", "category": "orders",
     "method": "POST", "path": "/mock/orders", "expected_status": 200,
     "headers": {"Authorization": "Bearer valid_token_abc", "Content-Type": "application/json"},
     "body": {"sku": "gold_100"}, "failure_mode": None},
    {"name": "Create order with missing sku", "category": "orders",
     "method": "POST", "path": "/mock/orders", "expected_status": 400,
     "headers": {"Authorization": "Bearer valid_token_abc", "Content-Type": "application/json"},
     "body": {}, "failure_mode": None},
    {"name": "Create order with unknown sku", "category": "orders",
     "method": "POST", "path": "/mock/orders", "expected_status": 404,
     "headers": {"Authorization": "Bearer valid_token_abc", "Content-Type": "application/json"},
     "body": {"sku": "nope_999"}, "failure_mode": "invalid-sku"},
    {"name": "Create order with invalid state", "category": "orders",
     "method": "POST", "path": "/mock/orders", "expected_status": 409,
     "headers": {"Authorization": "Bearer valid_token_abc", "Content-Type": "application/json"},
     "body": {"sku": "gold_100", "state": "shipped"}, "failure_mode": "invalid-order-state"},
    {"name": "Create order wrong method", "category": "orders",
     "method": "PUT", "path": "/mock/orders", "expected_status": 405,
     "headers": {"Authorization": "Bearer valid_token_abc", "Content-Type": "application/json"},
     "body": {"sku": "gold_100"}, "failure_mode": None},
    {"name": "Create order wrong content type", "category": "orders",
     "method": "POST", "path": "/mock/orders", "expected_status": 200,
     "headers": {"Authorization": "Bearer valid_token_abc"}, "body": {"sku": "gold_100"}, "failure_mode": "wrong-content-type"},
    {"name": "Create order that times out", "category": "orders",
     "method": "POST", "path": "/mock/orders", "expected_status": None,
     "headers": {"Authorization": "Bearer valid_token_abc", "Content-Type": "application/json"},
     "body": {"sku": "gold_100"}, "failure_mode": "timeout", "timeout_seconds": 3},
    # --- auth token ---
    {"name": "Issue auth token valid", "category": "auth",
     "method": "POST", "path": "/mock/auth/token", "expected_status": 200,
     "headers": {"Content-Type": "application/json"}, "body": {"client_id": "demo"}, "failure_mode": None},
    {"name": "Issue auth token missing field", "category": "auth",
     "method": "POST", "path": "/mock/auth/token", "expected_status": 400,
     "headers": {"Content-Type": "application/json"}, "body": {}, "failure_mode": "missing-field"},
    {"name": "Issue auth token malformed json", "category": "auth",
     "method": "POST", "path": "/mock/auth/token", "expected_status": 200,
     "headers": {"Content-Type": "application/json"}, "body": "not json", "failure_mode": "invalid-json"},
    # --- webhooks ---
    {"name": "Webhook with bad signature", "category": "webhooks",
     "method": "POST", "path": "/mock/webhooks/receive", "expected_status": 401,
     "headers": {"Content-Type": "application/json"}, "body": {"event": "purchase"}, "failure_mode": "bad-signature"},
    {"name": "Webhook duplicate event", "category": "webhooks",
     "method": "POST", "path": "/mock/webhooks/receive", "expected_status": 409,
     "headers": {"Content-Type": "application/json", "x-event-id": "evt_dup"},
     "body": {"event": "purchase"}, "failure_mode": "duplicate-webhook"},
]
